#nek pokemon
import turtle
def slika(z):
    "Nariše lepo sliko"
    z.speed(100)
    z.pensize(2)
    z.pencolor("black")
    z.fillcolor("orange")
    z.begin_fill()
    z.circle(200)
    z.end_fill()
    z.lt(90)
    z.penup()
    z.fd(300)
    z.pendown()
    z.fillcolor("white")
    z.begin_fill()
    z.circle(50)
    z.circle(5)
    z.penup()
    z.rt(90)
    z.fd(100)
    z.pendown()
    z.circle(50)
    z.circle(5)
    z.end_fill()
    z.rt(135)
    z.penup()
    z.fd(100)
    z.pendown()
    z.fillcolor("red")
    r = 5
    z.begin_fill()
    for i in range(9):
        z.circle(r)
        r+=10
    z.end_fill()
    z.penup()
    z.fd(200)
    z.fillcolor("orange")
    z.lt(45)
    z.pendown()
    z.begin_fill()
    z.fd(300)
    z.lt(90)
    z.fd(50)
    z.lt(90)
    z.fd(30)
    z.lt(90)
    z.fd(30)
    z.rt(90)
    z.fd(250)
    z.rt(90)
    z.penup()
    z.fd(200)
    z.rt(90)
    z.pendown()
    z.fd(230)
    z.lt(90)
    z.fd(50)
    z.lt(90)
    z.fd(30)
    z.lt(90)
    z.fd(30)
    z.rt(90)
    z.fd(200)
    z.end_fill()
    turtle.exitonclick()
    
slika(turtle.Turtle())